### ISSUE TITLE
Keine Funktion im Frontend?

### ISSUE THREAD

**Issue by FlowinBeatz** [heimrichhannot/contao-tab-control-bundle#1]
Nach Installation und anlegen der Content Elemente passiert im Frontend nichts.
Ich habe die ul-Liste inkl. Links, ich habe darunter die Inhalte der Tabs, aber sonst passiert nichts.
Es werden zwei JS-Dateien geladen: 

`<script src="bundles/contaotabcontrol/bootstrap-tabs.js?v=221d5155"></script><script src="bundles/contaotabcontrol/contao-tab-control-bundle.js?v=221d5155">`

Die Konsole schmeißt keinen Fehler. 
Was mache ich falsch?!

**Comment by koertho** [comment]
Hallo, hast du auch Bootstrap eingebunden? Das Bundle bringt nur zusätzliche Assets mit, Bootstrap muss selber eingebunden werden.

**Comment by Defcon0** [comment]
So ist es. Ich habe auch gerade die 1.0 herausgebracht und die Readme überarbeitet. Damit sollte es nun klarer sein ;-) Du musst vorher das bootstrap JavaScript eingebunden haben, dann sollte es klappen.

**Comment by FlowinBeatz** [comment]
Ich hatte es fast befürchtet. Es ging aus der Readme nicht ganz hervor und es lag die Vermutung nahe, dass einfach die entsprechenden Teile von Bootstrap in eine eigene JS extrahiert wurde. Danke für die schnelle Rückmeldung!
